name: 服务器自用构建 - dv 测试

on:
  workflow_dispatch:
#  push:

env:
  DOCKER_IMAGE: juijote/caddy
  PLATFORMS: linux/amd64 #,linux/arm64,linux/arm/v7

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest Caddy version
        id: caddy-version
        run: |
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r ".tag_name")
          # 删除 'v' 前缀
          CADDY_VERSION=${LATEST_VERSION#v}
          #CADDY_VERSION=2.9.1 # 指定版本
          echo "version=${CADDY_VERSION}" >> $GITHUB_OUTPUT
          echo "Latest Caddy version: ${CADDY_VERSION}"

      - name: Generate Dockerfile
        env:
          CADDY_VERSION: ${{ steps.caddy-version.outputs.version }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 访问私有库
        run: |
          cat > Dockerfile << EOF
          ARG CADDY_VERSION=${CADDY_VERSION}
          FROM caddy:\${CADDY_VERSION}-builder AS builder

          RUN git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

          RUN xcaddy build \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/caddy-dns/tencentcloud \
              --with github.com/greenpau/caddy-security \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/corazawaf/coraza-caddy/v2 \
              --with github.com/ueffel/caddy-brotli \
              --with github.com/caddyserver/transform-encoder \
              --with pkg.jsn.cam/caddy-defender \
              --with github.com/lum8rjack/caddy-ja4h \
              --with github.com/Juijote/caddy-cerberus \
              --with github.com/Juijote/Caddy-Device-Validator@ffb101e7d8ffe9708f20be0ab0cd92d2218d6cde

          FROM caddy:\${CADDY_VERSION}
          RUN apk add --no-cache tzdata
          COPY --from=builder /usr/bin/caddy /usr/bin/caddy
          EOF

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            CADDY_VERSION=${{ steps.caddy-version.outputs.version }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:server-20251102-dv
            ${{ env.DOCKER_IMAGE }}:server-20251102-dv${{ steps.caddy-version.outputs.version }}
            
