name: 服务器自用构建 - 测试 - waf

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: juijote/caddy
  PLATFORMS: linux/amd64 #,linux/arm64,linux/arm/v7

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest Caddy version
        id: caddy-version
        run: |
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r ".tag_name")
          # 删除 'v' 前缀
          #CADDY_VERSION=${LATEST_VERSION#v}
          CADDY_VERSION=2.9.1 # 指定版本
          echo "version=${CADDY_VERSION}" >> $GITHUB_OUTPUT
          echo "Latest Caddy version: ${CADDY_VERSION}"

      - name: Generate Dockerfile
        env:
          CADDY_VERSION: ${{ steps.caddy-version.outputs.version }}
        run: |
          cat > Dockerfile << EOF
          ARG CADDY_VERSION=${CADDY_VERSION}
          FROM caddy:\${CADDY_VERSION}-builder AS builder

          # 安装 caddy-waf 依赖
          RUN apk add --no-cache git wget

          # 下载 GeoLite2 数据库
          RUN wget -O /tmp/GeoLite2-Country.mmdb https://git.io/GeoLite2-Country.mmdb

          RUN GOTOOLCHAIN=go1.24.2 xcaddy build \
              --with github.com/fabriziosalmi/caddy-waf=./ \
              --with github.com/caddy-dns/cloudflare@v0.1.0 \
              --with github.com/caddy-dns/dnspod \
              --with github.com/greenpau/caddy-security \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/corazawaf/coraza-caddy/v2 \
              --with github.com/ueffel/caddy-brotli \
              --with github.com/caddyserver/transform-encoder \
              --with github.com/jasonlovesdoggo/caddy-defender \
              --with github.com/lum8rjack/caddy-ja4h@9a858a9 \
              --with github.com/Juijote/caddy-cerberus

          FROM caddy:\${CADDY_VERSION}
          RUN apk add --no-cache tzdata
          COPY --from=builder /usr/bin/caddy /usr/bin/caddy
          EOF

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            CADDY_VERSION=${{ steps.caddy-version.outputs.version }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:server-waf
            ${{ env.DOCKER_IMAGE }}:server-waf${{ steps.caddy-version.outputs.version }}
            
